//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Incube.Vision.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_en() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Incube.Vision.Properties.Resources_en", typeof(Resources_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Camera Calibration Position 的本地化字符串。
        /// </summary>
        internal static string CameraCab {
            get {
                return ResourceManager.GetString("CameraCab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Camera Basic Data 的本地化字符串。
        /// </summary>
        internal static string CameraData {
            get {
                return ResourceManager.GetString("CameraData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Camera Direction 的本地化字符串。
        /// </summary>
        internal static string CameraDir {
            get {
                return ResourceManager.GetString("CameraDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Camera MPP 的本地化字符串。
        /// </summary>
        internal static string CameraMpp {
            get {
                return ResourceManager.GetString("CameraMpp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Angle between the suction nozzle and the camera 的本地化字符串。
        /// </summary>
        internal static string DescripAngel {
            get {
                return ResourceManager.GetString("DescripAngel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Within the camera&apos;s field of view, the image rotates clockwise in a positive direction 的本地化字符串。
        /// </summary>
        internal static string DescripCameraDir {
            get {
                return ResourceManager.GetString("DescripCameraDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The suction nozzle rotates at the center of the fixed camera position 的本地化字符串。
        /// </summary>
        internal static string DescripCenter {
            get {
                return ResourceManager.GetString("DescripCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Whether the camera is aligned with the mechanical direction 的本地化字符串。
        /// </summary>
        internal static string DescripDirection {
            get {
                return ResourceManager.GetString("DescripDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 the camera&apos;s XY direction of suction nozzle&apos;s MPP 的本地化字符串。
        /// </summary>
        internal static string DescripMpp {
            get {
                return ResourceManager.GetString("DescripMpp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Related vision parameters of suction nozzle(pick) 的本地化字符串。
        /// </summary>
        internal static string DescripPick {
            get {
                return ResourceManager.GetString("DescripPick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 suction nozzle name 的本地化字符串。
        /// </summary>
        internal static string DescripPickerName {
            get {
                return ResourceManager.GetString("DescripPickerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Photo taken of the suction nozzle at the current mechanical position 的本地化字符串。
        /// </summary>
        internal static string DescripPixel {
            get {
                return ResourceManager.GetString("DescripPixel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Place-Parameters of the down-looking camera 的本地化字符串。
        /// </summary>
        internal static string DescripPlaceDn {
            get {
                return ResourceManager.GetString("DescripPlaceDn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Place-Parameters of the up-looking camera 的本地化字符串。
        /// </summary>
        internal static string DescripPlaceUp {
            get {
                return ResourceManager.GetString("DescripPlaceUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Suction nozzle to photograph the mechanical position 的本地化字符串。
        /// </summary>
        internal static string DescripPos {
            get {
                return ResourceManager.GetString("DescripPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 R Whether the direction is consistent or not 的本地化字符串。
        /// </summary>
        internal static string DescripRDir {
            get {
                return ResourceManager.GetString("DescripRDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The camera position in which the picture is taken 的本地化字符串。
        /// </summary>
        internal static string DescripTeachPos {
            get {
                return ResourceManager.GetString("DescripTeachPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Left suction nozzle vision parameters 的本地化字符串。
        /// </summary>
        internal static string DescripVisionSettingsL {
            get {
                return ResourceManager.GetString("DescripVisionSettingsL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Right suction nozzle vision parameters 的本地化字符串。
        /// </summary>
        internal static string DescripVisionSettingsR {
            get {
                return ResourceManager.GetString("DescripVisionSettingsR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 X Whether the direction is consistent or not 的本地化字符串。
        /// </summary>
        internal static string DescripXDir {
            get {
                return ResourceManager.GetString("DescripXDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The X direction&apos;pixel of the camera and the suction nozzle（MPP） 的本地化字符串。
        /// </summary>
        internal static string DescripXMpp {
            get {
                return ResourceManager.GetString("DescripXMpp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Y Whether the direction is consistent or not 的本地化字符串。
        /// </summary>
        internal static string DescripYDir {
            get {
                return ResourceManager.GetString("DescripYDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Y direction&apos;pixel of the camera and the suction nozzle（MPP） 的本地化字符串。
        /// </summary>
        internal static string DescripYMpp {
            get {
                return ResourceManager.GetString("DescripYMpp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Angel 的本地化字符串。
        /// </summary>
        internal static string DisplayAngel {
            get {
                return ResourceManager.GetString("DisplayAngel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Camera clockwise is positive 的本地化字符串。
        /// </summary>
        internal static string DisplayCameraDir {
            get {
                return ResourceManager.GetString("DisplayCameraDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Center of rotation 的本地化字符串。
        /// </summary>
        internal static string DisplayCenter {
            get {
                return ResourceManager.GetString("DisplayCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Direction 的本地化字符串。
        /// </summary>
        internal static string DisplayDirection {
            get {
                return ResourceManager.GetString("DisplayDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MPP 的本地化字符串。
        /// </summary>
        internal static string DisplayMpp {
            get {
                return ResourceManager.GetString("DisplayMpp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pick Vision 的本地化字符串。
        /// </summary>
        internal static string DisplayPick {
            get {
                return ResourceManager.GetString("DisplayPick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Suction Nozzle Name 的本地化字符串。
        /// </summary>
        internal static string DisplayPickerName {
            get {
                return ResourceManager.GetString("DisplayPickerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Photo results 的本地化字符串。
        /// </summary>
        internal static string DisplayPixel {
            get {
                return ResourceManager.GetString("DisplayPixel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Place-DnVision 的本地化字符串。
        /// </summary>
        internal static string DisplayPlaceDn {
            get {
                return ResourceManager.GetString("DisplayPlaceDn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Place-UpVision 的本地化字符串。
        /// </summary>
        internal static string DisplayPlaceUp {
            get {
                return ResourceManager.GetString("DisplayPlaceUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mechanical position 的本地化字符串。
        /// </summary>
        internal static string DisplayPos {
            get {
                return ResourceManager.GetString("DisplayPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 R-Dir 的本地化字符串。
        /// </summary>
        internal static string DisplayRDir {
            get {
                return ResourceManager.GetString("DisplayRDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Photo Location 的本地化字符串。
        /// </summary>
        internal static string DisplayTeachPos {
            get {
                return ResourceManager.GetString("DisplayTeachPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Left Vision Param 的本地化字符串。
        /// </summary>
        internal static string DisplayVisionSettingsL {
            get {
                return ResourceManager.GetString("DisplayVisionSettingsL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Right Vision Param 的本地化字符串。
        /// </summary>
        internal static string DisplayVisionSettingsR {
            get {
                return ResourceManager.GetString("DisplayVisionSettingsR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 X-Dir 的本地化字符串。
        /// </summary>
        internal static string DisplayXDir {
            get {
                return ResourceManager.GetString("DisplayXDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 X-Dir 的本地化字符串。
        /// </summary>
        internal static string DisplayXMpp {
            get {
                return ResourceManager.GetString("DisplayXMpp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Y-Dir 的本地化字符串。
        /// </summary>
        internal static string DisplayYDir {
            get {
                return ResourceManager.GetString("DisplayYDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Y-Dir 的本地化字符串。
        /// </summary>
        internal static string DisplayYMpp {
            get {
                return ResourceManager.GetString("DisplayYMpp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fixed Camera Data Base 的本地化字符串。
        /// </summary>
        internal static string FixedCameraData {
            get {
                return ResourceManager.GetString("FixedCameraData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Vision Param 的本地化字符串。
        /// </summary>
        internal static string VisionSettngs {
            get {
                return ResourceManager.GetString("VisionSettngs", resourceCulture);
            }
        }
    }
}
