//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Incube.Vision.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Incube.Vision.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 相机标定位置 的本地化字符串。
        /// </summary>
        internal static string CameraCab {
            get {
                return ResourceManager.GetString("CameraCab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机基础数据 的本地化字符串。
        /// </summary>
        internal static string CameraData {
            get {
                return ResourceManager.GetString("CameraData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机方向 的本地化字符串。
        /// </summary>
        internal static string CameraDir {
            get {
                return ResourceManager.GetString("CameraDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机MPP值 的本地化字符串。
        /// </summary>
        internal static string CameraMpp {
            get {
                return ResourceManager.GetString("CameraMpp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 吸嘴与相机夹角 的本地化字符串。
        /// </summary>
        internal static string DescripAngel {
            get {
                return ResourceManager.GetString("DescripAngel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在相机视野内，图像顺时针旋转为正方向 的本地化字符串。
        /// </summary>
        internal static string DescripCameraDir {
            get {
                return ResourceManager.GetString("DescripCameraDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 吸嘴在固定相机拍照位置的旋转中心 的本地化字符串。
        /// </summary>
        internal static string DescripCenter {
            get {
                return ResourceManager.GetString("DescripCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机与机械方向是否一致 的本地化字符串。
        /// </summary>
        internal static string DescripDirection {
            get {
                return ResourceManager.GetString("DescripDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 吸嘴与相机XY方向的像素当量 的本地化字符串。
        /// </summary>
        internal static string DescripMpp {
            get {
                return ResourceManager.GetString("DescripMpp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 吸嘴取料相关视觉参数 的本地化字符串。
        /// </summary>
        internal static string DescripPick {
            get {
                return ResourceManager.GetString("DescripPick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 吸嘴名称 的本地化字符串。
        /// </summary>
        internal static string DescripPickerName {
            get {
                return ResourceManager.GetString("DescripPickerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 吸嘴在当前机械位置的拍照结果 的本地化字符串。
        /// </summary>
        internal static string DescripPixel {
            get {
                return ResourceManager.GetString("DescripPixel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 吸嘴放料 下视相机相关参数 的本地化字符串。
        /// </summary>
        internal static string DescripPlaceDn {
            get {
                return ResourceManager.GetString("DescripPlaceDn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 吸嘴放料 上视相机相关参数 的本地化字符串。
        /// </summary>
        internal static string DescripPlaceUp {
            get {
                return ResourceManager.GetString("DescripPlaceUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 吸嘴拍照机械位置 的本地化字符串。
        /// </summary>
        internal static string DescripPos {
            get {
                return ResourceManager.GetString("DescripPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 R 方向是否一致 的本地化字符串。
        /// </summary>
        internal static string DescripRDir {
            get {
                return ResourceManager.GetString("DescripRDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 示教拍照位置的相机结果 的本地化字符串。
        /// </summary>
        internal static string DescripTeachPos {
            get {
                return ResourceManager.GetString("DescripTeachPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 左吸嘴视觉参数 的本地化字符串。
        /// </summary>
        internal static string DescripVisionSettingsL {
            get {
                return ResourceManager.GetString("DescripVisionSettingsL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 右吸嘴视觉参数 的本地化字符串。
        /// </summary>
        internal static string DescripVisionSettingsR {
            get {
                return ResourceManager.GetString("DescripVisionSettingsR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 X 方向是否一致 的本地化字符串。
        /// </summary>
        internal static string DescripXDir {
            get {
                return ResourceManager.GetString("DescripXDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 吸嘴与相机 X 方向像素当量（MPP） 的本地化字符串。
        /// </summary>
        internal static string DescripXMpp {
            get {
                return ResourceManager.GetString("DescripXMpp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Y 方向是否一致 的本地化字符串。
        /// </summary>
        internal static string DescripYDir {
            get {
                return ResourceManager.GetString("DescripYDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 吸嘴与相机 Y 方向像素当量（MPP） 的本地化字符串。
        /// </summary>
        internal static string DescripYMpp {
            get {
                return ResourceManager.GetString("DescripYMpp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 吸嘴与相机夹角 的本地化字符串。
        /// </summary>
        internal static string DisplayAngel {
            get {
                return ResourceManager.GetString("DisplayAngel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机顺时针为正方向 的本地化字符串。
        /// </summary>
        internal static string DisplayCameraDir {
            get {
                return ResourceManager.GetString("DisplayCameraDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 旋转中心 的本地化字符串。
        /// </summary>
        internal static string DisplayCenter {
            get {
                return ResourceManager.GetString("DisplayCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机与机械方向是否一致 的本地化字符串。
        /// </summary>
        internal static string DisplayDirection {
            get {
                return ResourceManager.GetString("DisplayDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 像素当量 的本地化字符串。
        /// </summary>
        internal static string DisplayMpp {
            get {
                return ResourceManager.GetString("DisplayMpp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取料视觉 的本地化字符串。
        /// </summary>
        internal static string DisplayPick {
            get {
                return ResourceManager.GetString("DisplayPick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 吸嘴名称 的本地化字符串。
        /// </summary>
        internal static string DisplayPickerName {
            get {
                return ResourceManager.GetString("DisplayPickerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拍照结果 的本地化字符串。
        /// </summary>
        internal static string DisplayPixel {
            get {
                return ResourceManager.GetString("DisplayPixel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 放料--下视觉 的本地化字符串。
        /// </summary>
        internal static string DisplayPlaceDn {
            get {
                return ResourceManager.GetString("DisplayPlaceDn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 放料--上视觉 的本地化字符串。
        /// </summary>
        internal static string DisplayPlaceUp {
            get {
                return ResourceManager.GetString("DisplayPlaceUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拍照机械位置 的本地化字符串。
        /// </summary>
        internal static string DisplayPos {
            get {
                return ResourceManager.GetString("DisplayPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 R-方向 的本地化字符串。
        /// </summary>
        internal static string DisplayRDir {
            get {
                return ResourceManager.GetString("DisplayRDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 示教拍照位置 的本地化字符串。
        /// </summary>
        internal static string DisplayTeachPos {
            get {
                return ResourceManager.GetString("DisplayTeachPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 左吸嘴视觉参数 的本地化字符串。
        /// </summary>
        internal static string DisplayVisionSettingsL {
            get {
                return ResourceManager.GetString("DisplayVisionSettingsL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 右吸嘴视觉参数 的本地化字符串。
        /// </summary>
        internal static string DisplayVisionSettingsR {
            get {
                return ResourceManager.GetString("DisplayVisionSettingsR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 X-方向 的本地化字符串。
        /// </summary>
        internal static string DisplayXDir {
            get {
                return ResourceManager.GetString("DisplayXDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 X-方向 的本地化字符串。
        /// </summary>
        internal static string DisplayXMpp {
            get {
                return ResourceManager.GetString("DisplayXMpp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Y-方向 的本地化字符串。
        /// </summary>
        internal static string DisplayYDir {
            get {
                return ResourceManager.GetString("DisplayYDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Y-方向 的本地化字符串。
        /// </summary>
        internal static string DisplayYMpp {
            get {
                return ResourceManager.GetString("DisplayYMpp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 固定相机基础数据 的本地化字符串。
        /// </summary>
        internal static string FixedCameraData {
            get {
                return ResourceManager.GetString("FixedCameraData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 视觉参数 的本地化字符串。
        /// </summary>
        internal static string VisionSettngs {
            get {
                return ResourceManager.GetString("VisionSettngs", resourceCulture);
            }
        }
    }
}
